import json
import tempfile
import unittest
from pathlib import Path
from PySide6.QtCore import QCoreApplication
from tests.test_business_logic import seeded
from app.group_dispatch import GroupStore
from app import sending_store as states


class ProfileGroupFlowTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):cls.app=QCoreApplication.instance() or QCoreApplication([])

    def test_multiselect_blank_counts_conditions_and_sort(self):
        with seeded(3) as b:
            p=b.profilesModule
            b.repo.update_profile_field('P2026169002A','微信','否')
            b.repo.update_profile_field('P2026169003A','微信','')
            b.repo.update_profile_field('P2026169001A','QQ','是')
            p.refresh()
            index=next(i for i,c in enumerate(p.tableModel.columns) if c[0]=='profile:微信')
            self.assertEqual({o['value']:o['count'] for o in p.columnFilterInfo(index)['options']},{'':1,'是':1,'否':1})
            p.setColumnFilter('profile:微信','values',['是',''],'')
            self.assertEqual(p.visibleCount,2)
            p.setColumnFilter('profile:QQ','empty',[],'')
            self.assertEqual([r['name'] for r in p.tableModel.rows],['学员3'])
            p.setColumnFilter('profile:QQ','clear',[],'')
            p.sortField('name',True)
            self.assertEqual([r['name'] for r in p.tableModel.rows],['学员3','学员1'])
            p.setColumnFilter('profile:微信','values',[],'')
            self.assertEqual(p.visibleCount,0)
            self.assertEqual(len(p.columnFilterInfo(index)['options']),3)
            p.clearFilters()
            p.setColumnFilter('name','contains',[],'2')
            self.assertEqual(p.selected['name'],'学员2')

    def test_filter_rechecks_after_edit_without_switching_editor(self):
        with seeded(2) as b:
            p=b.profilesModule
            p.setColumnFilter('profile:QQ','empty',[],'')
            key=p.selected['_record_key']
            self.assertTrue(p.saveEditorField(key,'QQ','是'))
            self.assertEqual(p.visibleCount,1)
            self.assertEqual(p.selected['_record_key'],key)
            self.assertNotIn(key,p.recipientKeys)

    def test_profile_filtered_list_rendered_snapshot_and_stale_guard(self):
        with seeded(3) as b:
            p,g=b.profilesModule,b.groupCenter
            p.setColumnFilter('name','values',['学员1','学员3'],'')
            keys=p.recipientKeys
            fields=[dict(type='text',text='{姓名}，请填写资料')]
            self.assertTrue(g.createFromProfiles('资料未齐名单',fields,keys))
            self.assertEqual([r['name'] for r in g.rows],['学员1','学员3'])
            self.assertEqual(g.rows[0]['message'],'学员1，请填写资料')
            self.assertEqual(g.selected['content_template'],fields)
            self.assertEqual(json.loads(g.rows[0]['learning_data'])['student_id'],'P2026169001A')
            self.assertEqual(b.workflow.batches,[])
            self.assertEqual(g.pendingCount,2)
            p.setColumnFilter('name','values',['学员2'],'')
            self.assertFalse(g.createFromProfiles('旧筛选不可创建',fields,keys))
            self.assertEqual(len(g.lists),1)
            self.assertEqual(len(g.store.plan(g.selected['id'])),2)

    def test_individual_mixed_content_edit_and_sent_immutable(self):
        with seeded(1) as b, tempfile.TemporaryDirectory() as folder:
            file=Path(folder)/'attachment.txt'
            # A test fixture generated by the test, not an application export.
            file.write_text('test attachment',encoding='utf-8')
            g=b.groupCenter
            initial=[dict(type='text',text='{姓名}原话术')]
            self.assertTrue(g.createStructured('测试','甲\n乙',initial))
            first,second=g.rows
            list_id=g.selected['id']
            self.assertTrue(g.prepare('',{}))
            updated=[dict(type='text',text='甲的独立话术'),dict(type='file',path=str(file)),dict(type='text',text='文件说明')]
            self.assertTrue(g.saveRecipientContent(list_id,first['id'],updated))
            self.assertFalse(g.preview)
            self.assertIsNone(g._confirmation)
            saved=json.loads(g.rows[0]['content'])
            self.assertEqual([item['text'] if item['type']=='text' else item['path'] for item in saved],
                             [item['text'] if item['type']=='text' else item['path'] for item in updated])
            self.assertTrue(all(item.get('personal_override') for item in saved))
            self.assertEqual(json.loads(g.rows[1]['content']),[dict(type='text',text='乙原话术',template='{姓名}原话术')])
            self.assertEqual([c[1] for c in g.pendingModel.columns][:4],['名字','话术1','文件1','话术2'])
            task=g.store.plan(list_id)[0]
            attempt=g.store.claim(list_id,task)
            g.store.finish(list_id,task,attempt,states.SENT,'测试桩，无实际发送')
            g.refresh()
            self.assertEqual((g.pendingCount,g.sentCount),(1,1))
            self.assertFalse(g.saveRecipientContent(list_id,first['id'],initial))
            self.assertFalse(g.saveRecipientContent(list_id+1,second['id'],initial))
            self.assertTrue(g.saveContent(list_id,[dict(type='text',text='统一新话术')]))
            protected_items=json.loads(g.rows[0]['content'])
            self.assertEqual([item['text'] if item['type']=='text' else item['path'] for item in protected_items],
                             [item['text'] if item['type']=='text' else item['path'] for item in updated])
            self.assertTrue(all(item.get('personal_override') for item in protected_items))
            self.assertEqual(g.rows[1]['message'],'统一新话术')
            reopened=GroupStore(g.store.path)
            reopened_items=json.loads(reopened.rows(list_id)[0]['content'])
            self.assertTrue(all(item.get('personal_override') for item in reopened_items))

    def test_copy_batch_templates_bulk_protection_mixed_fields_and_history_isolation(self):
        with seeded(2) as b, tempfile.TemporaryDirectory() as folder:
            attachment=Path(folder)/'lesson.txt'
            attachment.write_text('temporary fixture',encoding='utf-8')
            b.repo.update_profile_field('P2026169001A','微信','是')
            b.repo.update_profile_field('P2026169002A','微信','否')
            p,g=b.profilesModule,b.groupCenter
            fields=[dict(type='text',text='{姓名}-{微信}'),dict(type='file',path=str(attachment))]
            self.assertTrue(g.createFromProfiles('可复制名单',fields,p.recipientKeys),g.status)
            list_id=g.selected['id']
            first,second=g.rows

            # A cell-level edit is marked and default whole-column updates preserve it.
            self.assertTrue(g.saveRecipientContent(list_id,first['id'],[dict(type='text',text='个人话术'),dict(type='file',path=str(attachment))]),g.status)
            self.assertTrue(g.bulkField(list_id,0,dict(type='text',text='{姓名}-统一-{微信}'),False),g.status)
            self.assertIn('个人话术',g.rows[0]['message'])
            second_learning=json.loads(second['learning_data'])
            second_wechat=second_learning['profile_fields']['微信']
            self.assertTrue(g.rows[1]['message'].startswith(f"{second['name']}-统一-{second_wechat}"))
            self.assertTrue(json.loads(g.rows[0]['content'])[0].get('personal_override',False))

            # Newly appended text follows the file column, preserving mixed send order.
            self.assertTrue(g.appendField(dict(type='text',text='补充-{姓名}')),g.status)
            second_items=json.loads(g.store.rows(list_id)[1]['content'])
            self.assertEqual([x['type'] for x in second_items],['text','file','text'])
            self.assertIn('补充-学员2',second_items[2]['text'])
            g.store.move_field(list_id,2,-1)
            self.assertEqual([x['type'] for x in json.loads(g.store.rows(list_id)[1]['content'])],['text','text','file'])
            g.store.move_field(list_id,1,1)
            self.assertEqual([x['type'] for x in json.loads(g.store.rows(list_id)[1]['content'])],['text','file','text'])
            g.store.remove_field(list_id,2)
            self.assertEqual([x['type'] for x in json.loads(g.store.rows(list_id)[1]['content'])],['text','file'])
            g.store.append_field(list_id,dict(type='text',text='补充-{姓名}'))

            # Record one mocked completion directly through the store, never using the desktop sender.
            task=next(t for t in g.store.plan(list_id) if t['name']=='学员2')
            attempt=g.store.claim(list_id,task)
            self.assertIsNotNone(attempt)
            g.store.finish(list_id,task,attempt,states.SENT,'临时验证：未调用实际发送')
            sent_before=json.loads(next(r for r in g.store.rows(list_id) if r['name']=='学员2')['content'])

            # Re-render the original template against current profile values in a separate fresh batch.
            b.repo.update_profile_field('P2026169001A','微信','否')
            b.repo.update_profile_field('P2026169002A','微信','是')
            old_records=len([1 for _ in g.store.rows(list_id)])
            self.assertTrue(g.copyList('复制的新名单',True),g.status)
            copied_id=g.selected['id']
            self.assertNotEqual(copied_id,list_id)
            self.assertTrue(all(r['state']=='待发送' for r in g.store.rows(copied_id)))
            copied={r['name']:json.loads(r['content']) for r in g.store.rows(copied_id)}
            latest_first=b.repo.get('P2026169001A')['profile_fields']['微信']
            latest_second=b.repo.get('P2026169002A')['profile_fields']['微信']
            self.assertEqual(copied['学员1'][0]['text'],'个人话术')
            self.assertTrue(copied['学员1'][0].get('personal_override'))
            self.assertEqual([x['type'] for x in copied['学员1']],['text','file','text'])
            self.assertEqual(copied['学员2'][0]['text'],f"学员2-统一-{latest_second}")
            # Later edits only affect the still-pending recipient; sent history remains byte-for-byte frozen.
            self.assertEqual(g.store.bulk_field(list_id,0,dict(type='text',text='后续-{姓名}'),override_personal=True),1)
            self.assertFalse(json.loads(next(r for r in g.store.rows(list_id) if r['name']=='学员1')['content'])[0].get('personal_override',False))
            g.store.append_field(list_id,dict(type='text',text='新字段'))
            sent_after=json.loads(next(r for r in g.store.rows(list_id) if r['name']=='学员2')['content'])
            self.assertEqual(sent_after,sent_before)
            with g.store.connect() as conn:
                self.assertEqual(conn.execute('SELECT count(*) FROM attempts WHERE recipient_id IN (SELECT id FROM recipients WHERE list_id=?)',(list_id,)).fetchone()[0],1)
                self.assertEqual(conn.execute('SELECT count(*) FROM attempts WHERE recipient_id IN (SELECT id FROM recipients WHERE list_id=?)',(copied_id,)).fetchone()[0],0)
            self.assertEqual(len(g.store.rows(list_id)),old_records)
            self.assertTrue(g.copyList('只复制名单',False),g.status)
            self.assertTrue(all(json.loads(r['content'])==[] and r['state']=='待发送' for r in g.rows))

    def test_unresolved_template_rejected_without_partial_changes(self):
        with seeded(2) as b:
            g=b.groupCenter
            self.assertTrue(g.createStructured('变量检查','甲\n乙',[dict(type='text',text='原消息')]))
            list_id=g.selected['id']
            before=[r['message'] for r in g.store.rows(list_id)]
            self.assertFalse(g.bulkField(list_id,0,dict(type='text',text='{缺失字段}'),False))
            self.assertIn('缺少变量字段',g.status)
            self.assertEqual([r['message'] for r in g.store.rows(list_id)],before)

    def test_single_cell_change_keeps_other_cells_and_table_stable(self):
        with seeded(1) as b:
            g=b.groupCenter
            self.assertTrue(g.createStructured('逐格编辑','甲\n乙',[
                dict(type='text',text='首句-{姓名}'),dict(type='text',text='第二句')]))
            list_id=g.selected['id'];recipient_id=g.rows[0]['id']
            resets=[]
            g.pendingModel.modelReset.connect(lambda:resets.append(1))
            g._notice='仅更新状态提示';g.changed.emit()
            self.assertEqual(resets,[])
            self.assertTrue(g.saveRecipientField(list_id,recipient_id,0,dict(type='text',text='单独-{姓名}')),g.status)
            self.assertEqual(resets,[])
            first=json.loads(g.rows[0]['content']);second=json.loads(g.rows[1]['content'])
            self.assertEqual(first[0]['text'],'单独-甲')
            self.assertTrue(first[0]['personal_override'])
            self.assertEqual(first[1]['text'],'第二句')
            self.assertFalse(first[1].get('personal_override',False))
            self.assertEqual(second[0]['text'],'首句-乙')
            self.assertNotIn('个人修改',g.pendingModel.get(0)['message_0'])
            reopened=GroupStore(g.store.path)
            self.assertEqual(json.loads(reopened.rows(list_id)[0]['content']),first)

    def test_legacy_batch_without_saved_template_copies_per_person_content(self):
        with seeded(1) as b:
            g=b.groupCenter
            self.assertTrue(g.createCustom('旧格式名单','甲|甲的旧消息\n乙|乙的旧消息'))
            old_id=g.selected['id']
            with g.store.connect() as conn:
                conn.execute("UPDATE lists SET content_template='[]' WHERE id=?",(old_id,))
            self.assertTrue(g.copyList('兼容复制',True),g.status)
            copied={r['name']:r['message'] for r in g.rows}
            self.assertIn('甲的旧消息',copied['甲'])
            self.assertIn('乙的旧消息',copied['乙'])
            self.assertTrue(all(r['state']=='待发送' for r in g.rows))

    def test_uncertain_and_paste_only_records_not_editable(self):
        with seeded(1) as b:
            g=b.groupCenter
            g.createCustom('保护状态','甲|原消息')
            row=g.rows[0]
            for state in (states.UNKNOWN,states.RUNNING,'仅粘贴未发送'):
                with g.store.connect() as conn:conn.execute('UPDATE recipients SET state=? WHERE id=?',(state,row['id']))
                self.assertFalse(g.saveRecipientContent(g.selected['id'],row['id'],[dict(type='text',text='不能写入')]))
                self.assertEqual(g.rows[0]['message'],'原消息')


if __name__=='__main__':unittest.main()
