const {chromium}=require('playwright');
const assert=require('assert');
const path=require('path');
const fs=require('fs');
const {pathToFileURL}=require('url');
const output=path.resolve(__dirname,'../output/overview');
fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 try {
 const page=await browser.newPage({viewport:{width:1280,height:820}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.join(__dirname,'learning-overview-local.html')).href);
 await page.waitForFunction(()=>document.querySelectorAll('#rows tr').length>0);
 assert(await page.locator('#latest-page').isVisible());
 assert.strictEqual(await page.locator('#tab-history').getAttribute('aria-selected'),'true');
 assert.strictEqual(await page.locator('#history-batch').inputValue(),'16');
 for(const id of ['history-batch','current','baseline','goal-batch'])assert.strictEqual(await page.locator('#'+id+' option').count(),17);
 assert.strictEqual(await page.locator('#latest-completion-rows tr').last().locator('td:nth-child(2)').textContent(),'13');
 assert.strictEqual(await page.locator('#latest-completion-rows tr').last().locator('td:nth-child(4)').textContent(),'3');
 assert((await page.locator('#latest-followup-summary').textContent()).includes('尚未填写 0人'));
 await page.screenshot({path:path.join(output,'history-16-1280.png'),fullPage:true});
 await page.selectOption('#history-batch','9');
 const historical=await page.evaluate(()=>{const c=singleBatch();return {id:c.id,lessons:c.lessons.length,total:c.completionTotal,buckets:c.completion.length,yes:c.completion.reduce((n,r)=>n+r.followable,0),marked:c.followupSummary.marked,people:c.completion.reduce((n,r)=>n+r.people,0)}});
 assert.strictEqual(historical.id,9);assert.strictEqual(historical.people,historical.total);assert.strictEqual(historical.marked,historical.total);assert(historical.yes>0);
 assert.strictEqual(await page.locator('#latest-rows tr').count(),historical.lessons);
 assert.strictEqual(await page.locator('#latest-completion-rows tr').count(),historical.buckets);
 assert((await page.locator('#latest-title').textContent()).includes('第9次'));
 assert.strictEqual(await page.locator('#current').inputValue(),'16');
 await page.screenshot({path:path.join(output,'history-9-1280.png'),fullPage:true});
 await page.selectOption('#history-batch','1');
 assert(await page.locator('#latest-learning-note').isVisible());
 assert((await page.locator('#latest-learning-note').textContent()).includes('未保存累计学习快照'));
 assert((await page.locator('#latest-rows').textContent()).includes('暂无累计学习快照'));
 assert(!(await page.locator('#single-charts').isVisible()));
 assert(await page.locator('#latest-completion-rows tr').count()>1);
 assert((await page.locator('#latest-completion-rows td:nth-child(4)').allTextContents()).every(x=>x==='—'));
 await page.screenshot({path:path.join(output,'history-1-1280.png'),fullPage:true});
 await page.selectOption('#history-batch','16');
 await page.click('#tab-compare');
 const latest=await page.locator('#current').inputValue();
 const trueLatest=await page.evaluate(()=>String(dashboardBatch().id));
 assert.strictEqual(trueLatest,'17');assert.strictEqual(await page.locator('#baseline').inputValue(),'9');
 const followComparison=await page.evaluate(()=>{const c=selected(current),b=selected(baseline);return c.completion.map(r=>{const x=b.completion.find(x=>x.count===r.count);return [String(r.followable??'—'),String(x?.followable??'—'),x&&r.followable!=null&&x.followable!=null?(r.followable-x.followable>0?'+':'')+(r.followable-x.followable)+'人':'—']})});
 for(let i=0;i<followComparison.length;i++)assert.deepStrictEqual(await page.locator('#distribution-rows tr').nth(i).locator('td:nth-child(n+8)').allTextContents(),followComparison[i]);
 const distribution=await page.evaluate(()=>{const c=selected(current);return {total:c.completionTotal,people:c.completion.reduce((n,r)=>n+r.people,0),highest:c.completion[0].count,buckets:c.completion.length,followable:c.completion.every(r=>r.followable==null||r.followable<=r.people)}});
 assert.strictEqual(distribution.people,distribution.total);assert(distribution.followable);
 assert.strictEqual(await page.locator('#completion-rows tr').count(),distribution.buckets);
 assert.strictEqual(await page.locator('#completion-rows tr').last().locator('td:nth-child(7)').textContent(),'100.00%');
 assert.strictEqual(await page.locator('#completion-rows tr').first().locator('td:nth-child(5)').textContent(),'');
 assert(await page.locator('#comparison-page').isVisible());assert(!(await page.locator('#goals-page').isVisible()));
 await page.selectOption('#baseline','12');
 assert.strictEqual(await page.locator('#compare-lesson').inputValue(),'4');
 assert((await page.locator('#cards').textContent()).includes('第4节'));
 const actual=await page.evaluate(()=>{const a=selected(current),b=selected(baseline),chart=charts[0].getOption(),gap=charts[1].getOption();return {
  seriesMatch:chart.series[0].data.every((v,i)=>v===a.lessons[i].course)&&chart.series[2].data.every((v,i)=>v===(b.lessons.find(x=>x.lesson===a.lessons[i].lesson)?.course??null)),
  names:chart.series.map(s=>s.name),tooltip:chart.tooltip[0].formatter([{dataIndex:0}]),
  marks:gap.series[0].markLine.data.map(x=>x.yAxis)
 }});
 assert.strictEqual(await page.locator('#distribution-rows tr').first().locator('td:nth-child(3)').textContent(),'—');
 assert(actual.seriesMatch);assert(actual.names.some(x=>x.includes('第12次')));assert(actual.tooltip.includes('变化'));assert(actual.tooltip.includes('第12次'));assert.deepStrictEqual(actual.marks,[5,10,15]);
 assert.strictEqual(await page.locator('#rows tr').last().locator('td:nth-child(3)').textContent(),'—');
 assert.strictEqual(await page.locator('#rows tr').last().locator('td:nth-child(4)').getAttribute('title'),'对比批次无该节快照');
 await page.selectOption('#current','12');await page.selectOption('#baseline','11');
 assert((await page.locator('#comparison-notice').textContent()).includes('分母不同'));
 await page.selectOption('#baseline','12');
 assert((await page.locator('#comparison-notice').textContent()).includes('变化为0'));
 assert((await page.locator('#completion-rows td:nth-child(4)').allTextContents()).every(x=>x==='—'));

 assert((await page.locator('#distribution-rows td:nth-child(4)').allTextContents()).every(x=>x==='0人'));
 for(const nth of [4,7,10])assert((await page.locator('#rows tr td:nth-child('+nth+')').allTextContents()).every(x=>x==='0.00pp'));
 await page.selectOption('#current',latest);await page.selectOption('#baseline','14');
 const cards=await page.locator('#cards').textContent();
 await page.click('#tab-goals');assert(await page.locator('#goals-page').isVisible());assert(!(await page.locator('#baseline').isVisible()));
 assert.strictEqual(await page.locator('#goal-batch').inputValue(),latest);
 await page.selectOption('#goal-lesson','2');
 assert((await page.locator('#trend-note').textContent()).includes('第1～2节'));
 assert((await page.locator('#trend-detail').textContent()).includes('第2节'));
 await page.selectOption('#trend-metric','homework');assert((await page.locator('#trend-note').textContent()).includes('作业率'));
 await page.fill('#homework-target','100');assert((await page.locator('#homework-goal').textContent()).includes('需再完成'));
 const marker=await page.evaluate(()=>charts[2].getOption().series[0].markLine.data[0].yAxis);assert.strictEqual(marker,100);
 await page.fill('#course-target','101');assert((await page.locator('#course-goal').textContent()).includes('0～100'));
 await page.fill('#course-target','85');await page.fill('#homework-target','85');
 assert.strictEqual(await page.locator('#cards').textContent(),cards);
 const goalText=await page.locator('#homework-goal').textContent();
 await page.click('#tab-compare');await page.selectOption('#baseline','12');
 await page.click('#tab-goals');assert.strictEqual(await page.locator('#homework-goal').textContent(),goalText);
 assert.strictEqual(await page.locator('#goal-lesson').inputValue(),'2');
 await page.selectOption('#goal-batch','12');assert.strictEqual(await page.locator('#current').inputValue(),latest);
 await page.selectOption('#goal-batch',latest);await page.selectOption('#trend-metric','gap');await page.selectOption('#goal-lesson','2');
 await page.screenshot({path:path.join(output,'goals-1280.png'),fullPage:true});
 await page.setViewportSize({width:1000,height:700});await page.waitForTimeout(200);
 assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)));
 await page.screenshot({path:path.join(output,'goals-1000.png'),fullPage:true});
 await page.click('#tab-compare');
 await page.locator('#tab-compare').focus();await page.keyboard.press('ArrowRight');assert(await page.locator('#goals-page').isVisible());await page.keyboard.press('ArrowLeft');assert(await page.locator('#comparison-page').isVisible());
 await page.click('#nav-workbench');assert(await page.locator('#workbench').isVisible());await page.click('#back-overview');assert(await page.locator('#comparison-page').isVisible());
 await page.evaluate(()=>charts[0].dispatchAction({type:'dataZoom',start:40,end:100}));assert((await page.locator('#detail').textContent()).includes('第12次'));
 await page.evaluate(()=>charts[0].dispatchAction({type:'dataZoom',start:0,end:100}));
 await page.screenshot({path:path.join(output,'overview-1000.png'),fullPage:true});
 await page.setViewportSize({width:1280,height:820});await page.waitForTimeout(200);
 await page.screenshot({path:path.join(output,'overview-1280.png'),fullPage:true});
 await page.click('#tab-latest');
 assert(await page.locator('#latest-page').isVisible());assert(!(await page.locator('#current').isVisible()));assert(!(await page.locator('#goal-batch').isVisible()));
 const latestData=await page.evaluate(()=>{const c=dashboardBatch();return {id:c.id,total:c.total,lessons:c.lessons.length,last:c.lessons.at(-1),match:charts[3].getOption().series[0].data.every((v,i)=>v===c.lessons[i].course),series:charts[3].getOption().series.length}});
 assert.strictEqual(String(latestData.id),trueLatest);assert(latestData.match);assert.strictEqual(latestData.series,2);
 assert(!(await page.locator('#history-batch').isVisible()));
 assert((await page.locator('#latest-followup-summary').textContent()).includes('尚未填写'));
 assert.strictEqual(await page.locator('#latest-rows tr').count(),latestData.lessons);
 assert.strictEqual(await page.locator('#latest-completion-rows tr').count(),distribution.buckets);
 const expectedFollowup=await page.evaluate(()=>dashboardBatch().completion.map(r=>String(r.followable??'—')));
 assert.deepStrictEqual(await page.locator('#latest-completion-rows tr td:nth-child(4)').allTextContents(),expectedFollowup);
 const latestCards=await page.locator('#latest-cards').textContent();assert(latestCards.includes(String(latestData.last.courseDone)+'人'));assert(latestCards.includes('导出')===false);
 await page.click('#tab-history');await page.selectOption('#history-batch','9');await page.click('#tab-latest');
 assert.strictEqual(await page.locator('#latest-cards').textContent(),latestCards);
 await page.screenshot({path:path.join(output,'latest-1280.png'),fullPage:true});
 await page.setViewportSize({width:1000,height:700});await page.waitForTimeout(200);
 assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)));
 await page.screenshot({path:path.join(output,'latest-1000.png'),fullPage:true});
 await page.click('#tab-compare');await page.selectOption('#current','12');await page.click('#tab-latest');
 assert.strictEqual(await page.locator('#latest-cards').textContent(),latestCards);
 await page.locator('#tab-latest').focus();await page.keyboard.press('End');assert(await page.locator('#goals-page').isVisible());await page.keyboard.press('Home');assert(await page.locator('#latest-page').isVisible());
 await page.click('#nav-workbench');await page.click('#back-overview');assert(await page.locator('#latest-page').isVisible());
 await page.click('#tab-compare');
 // A synthetic old snapshot with no learning rows must not produce estimated comparisons.
 await page.evaluate(()=>{DATA.batches.push({id:999,time:'demo',total:10,lessons:[]});option(baseline,999,'缺少数据样例');baseline.value='999';render(true)});
 assert.strictEqual(await page.locator('#compare-lesson option').count(),0);
 assert((await page.locator('#cards').textContent()).includes('暂无共同节次'));
 await page.evaluate(()=>{option(current,999,'缺少数据样例');current.value='999';render(true)});
 assert((await page.locator('#completion-rows').textContent()).includes('暂无'));
 assert.deepStrictEqual(errors,[]);
 console.log(JSON.stringify({passed:true,checks:['all 17 batches selectable','historical batch 9 manual flags','batch 16 exact zero bucket 13 / 3','old counts without cumulative rates','unmarked versus confirmed no','independent tabs and selectors','latest shared lesson','actual series and tooltip comparisons','5/10/15 bands','missing historical lesson','same batch zero deltas','different denominators','target validation and line','consistent trend lesson','keyboard tabs','navigation and zoom','two viewport sizes','no shared lesson fallback','completion totals and >=k rates','exact completion followup counts in targets scope','distribution and followable comparisons','actual latest 17 unaffected by historical selection','latest responsive and keyboard navigation'],pageErrors:errors}));
 } finally {await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
