const {chromium}=require('playwright');
const assert=require('assert');
const path=require('path');
const fs=require('fs');
const {pathToFileURL}=require('url');
const root=path.resolve(__dirname,'..');
const output=path.join(root,'output','overview');
fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const page=await browser.newPage({viewport:{width:1280,height:820}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.join(__dirname,'learning-overview-local.html')).href);
 await page.waitForFunction(()=>document.querySelectorAll('#rows tr').length>0);
 const initial=await page.evaluate(()=>({batch:document.querySelector('#current').value,rows:document.querySelectorAll('#rows tr').length,total:document.querySelector('#scope').textContent}));
 await page.selectOption('#current','12');await page.selectOption('#baseline','11');
 assert.strictEqual(await page.locator('#current').inputValue(),'12');
 const different=await page.locator('#comparison-notice').textContent();assert(different.includes('分母不同'));
 await page.selectOption('#baseline','12');
 assert((await page.locator('#comparison-notice').textContent()).includes('变化为0'));
 const deltas=await page.locator('#rows tr td:nth-child(3)').allTextContents();assert(deltas.every(x=>x==='0.00pp'));
 await page.fill('#homework-target','100');assert((await page.locator('#homework-goal').textContent()).includes('需再完成'));
 await page.fill('#course-target','101');assert((await page.locator('#course-goal').textContent()).includes('0～100'));
 await page.fill('#course-target','85');await page.fill('#homework-target','85');
 await page.selectOption('#current',initial.batch);await page.selectOption('#baseline','12');
 await page.selectOption('#goal-lesson','1');assert((await page.locator('#trend-note').textContent()).includes('第1节'));
 await page.selectOption('#goal-lesson',String(initial.rows));
 await page.click('#nav-workbench');assert(await page.locator('#workbench').isVisible());assert(!(await page.locator('#overview').isVisible()));
 await page.click('#back-overview');assert(await page.locator('#overview').isVisible());
 await page.evaluate(()=>{const ch=echarts.getInstanceByDom(document.querySelector('#rate-chart'));ch.dispatchAction({type:'dataZoom',start:40,end:100})});
 assert((await page.locator('#detail').textContent()).includes('第'));
 await page.evaluate(()=>echarts.getInstanceByDom(document.querySelector('#rate-chart')).dispatchAction({type:'dataZoom',start:0,end:100}));
 await page.screenshot({path:path.join(output,'overview-1280.png'),fullPage:true});
 await page.setViewportSize({width:1000,height:700});await page.waitForTimeout(250);
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert(!overflow);
 await page.screenshot({path:path.join(output,'overview-1000.png'),fullPage:true});
 assert.deepStrictEqual(errors,[]);
 console.log(JSON.stringify({passed:true,batches:await page.locator('#current option').count(),lessons:initial.rows,checks:['batch switch','baseline zero deltas','different denominators','target input validation','same-lesson trend','navigation','zoom','1280 and 1000 layout'],pageErrors:errors}));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
