"""接口固定参数，不属于用户配置。"""

COMPLETION = {'base_url': 'https://xs.jihuaxueyuan.com',
 'timeout': 30,
 'page_size': 500,
 'select_type': 'liveorrelive30min',
 'server_retries': 2,
 'retry_delay': 1,
 'auth': {'login_path': '/jihua/auth/dingtalk/ODg4OA',
          'dingtalk_base_url': 'https://login.dingtalk.com',
          'oauth_url': 'https://oapi.dingtalk.com/connect/oauth2/sns_authorize',
          'app_id': 'dingbyrgij7ipkdxdknc',
          'country_code': '+86',
          'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like '
                        'Gecko) Chrome/138.0.0.0 Safari/537.36 Edg/138.0.0.0',
          'ara_appkey': '1917',
          'ara_token': '0#19171753686591613322622626821754378296925776G6C0D512CD373977946CF199753BA219F0CC987'},
 'headers': {'accept': 'application/json, text/javascript, */*; q=0.01',
             'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
             'content-type': 'application/x-www-form-urlencoded',
             'priority': 'u=1, i',
             'sec-ch-ua': '"Microsoft Edge";v="153", "Not_A Brand";v="8", "Chromium";v="153"',
             'sec-ch-ua-mobile': '?0',
             'sec-ch-ua-platform': '"Windows"',
             'sec-fetch-dest': 'empty',
             'sec-fetch-mode': 'cors',
             'sec-fetch-site': 'same-origin',
             'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, '
                           'like Gecko) Chrome/153.0.0.0 Safari/537.36 Edg/153.0.0.0',
             'x-requested-with': 'XMLHttpRequest'},
 'filters': {'isAsc': 'asc',
             'studentNo': '',
             'nickname': '',
             'mobile': '',
             'xeuid': '',
             'status': '',
             'params[finishCount]': '',
             'params[actionStatus]': '',
             'params[absenceLiveClassNoS]': '',
             'params[absenceLiveClassNoE]': '',
             'params[agreedCompensationLiveTimeS]': '',
             'params[agreedCompensationLiveTimeE]': '',
             'homeworkFocus': ''}}

HOMEWORK = {'base_url': 'http://124.221.200.10',
 'timeout': 30,
 'auth': {'role': 'admin'},
 'headers': {'Accept': 'application/json, text/plain, */*',
             'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
             'Content-Type': 'application/json',
             'Proxy-Connection': 'keep-alive',
             'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, '
                           'like Gecko) Chrome/153.0.0.0 Safari/537.36 Edg/153.0.0.0'}}
